const { Roles } = require('./Users/Roles');
const { createCompaniesTable } = require('./Users/companyModel');
const { createUserTypesTable } = require('./Users/userTypeModel');
const { createUsersTable } = require('./Users/userModel');
const { createTokenTable } = require('./Token/tokenModel');
const { PasswordResets } = require('./Users/PasswordResets');

const { Units } = require('./InventoryManagement/Units');
const { ProductCategoriesTable } = require('./InventoryManagement/ProductCategories');
const { ProductTable } = require('./InventoryManagement/Products');
const { Warehouses } = require('./InventoryManagement/Warehouses');
const { ProductStockPerWarehouse } = require('./InventoryManagement/ProductStockPerWarehouse');
const { StockMovements } = require('./InventoryManagement/StockMovements');
const { Suppliers } = require('./InventoryManagement/Suppliers');
const { PurchaseOrders } = require('./InventoryManagement/PurchaseOrders');
const { PurchaseOrderItems } = require('./InventoryManagement/PurchaseOrderItems');
const { Customers } = require('./InventoryManagement/Customers');
const { SalesOrders } = require('./InventoryManagement/SalesOrders');
const { SalesOrderItems } = require('./InventoryManagement/SalesOrderItems');
const { Taxes } = require('./InventoryManagement/Taxes');
const { ProductTaxMap } = require('./InventoryManagement/ProductTaxMap');
const { AuditLogs } = require('./InventoryManagement/AuditLogs');
const { ProfitLossReports } = require('./InventoryManagement/ProfitLossReports');

const { LeadSources } = require('./CrmModels/LeadSources');
const { ProductCategories } = require('./CrmModels/ProductCategories');
const { FollowupTypes } = require('./CrmModels/FollowupTypes');
const { Industries } = require('./CrmModels/Industries');
const { SalesStages } = require('./CrmModels/SalesStages');
const { TaskTypes } = require('./CrmModels/TaskTypes');
const { Accounts } = require('./CrmModels/Accounts');
const { Contacts } = require('./CrmModels/Contacts');
const { Leads } = require('./CrmModels/Leads');
const { Opportunities } = require('./CrmModels/Opportunities');
const { Presales } = require('./CrmModels/Presales');
const { Comments } = require('./CrmModels/Comments');
const { PresalesAssignments } = require('./CrmModels/PresalesAssignments');
const { Groups } = require('./CrmModels/Groups');
const { GroupMembers } = require('./CrmModels/GroupMembers');
const { Assignments } = require('./CrmModels/Assignments');
const { EntityVisibility } = require('./CrmModels/EntityVisibility');

const initModels = async () => {
  await Roles();
  await createCompaniesTable();
  await createUserTypesTable();
  await createUsersTable();
  await createTokenTable();
  await PasswordResets();
  await Units();
  await ProductCategoriesTable();
  await ProductTable();
  await Warehouses();
  await ProductStockPerWarehouse();
  await StockMovements();
  await Suppliers();
  await PurchaseOrders();
  await PurchaseOrderItems();
  await Customers();
  await SalesOrders();
  await SalesOrderItems();
  await Taxes();
  await ProductTaxMap();
  await AuditLogs();
  await ProfitLossReports();
  await TaskTypes();
  await LeadSources();
  await ProductCategories();
  await FollowupTypes();
  await Industries();
  await SalesStages();
  await Accounts();
  await Contacts();
  await Leads();
  await Opportunities();
  await Presales();
  await Comments();
  await PresalesAssignments();
  await Groups();
  await GroupMembers();
  await Assignments();
  await EntityVisibility();
};

module.exports = { initModels };
